# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67c6626dfe684413ec1599c703e6d280a72045c25cc0d39592a4fd48e5aa1be9b2268d51fcbafd483bb864a4930730634e997de4db1edd009ef67c3400db1497

test:
  secret_key_base: e3e0c27d8461c4b9eec16bcfdaaccb45b266f4aa689bb758a73bcca5fff9fce9e39f5f2cf5657edb4ee54ce9915285f5ca45bc42b78e4127e629baec307d2175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
